[package]
name = "rust-demo"
version = "0.1.0"
authors = ["Bermular tech"]
edition = "2018"

[dependencies]
cron = "0.6.0"
chrono = "0.4.6"
rocket = "0.4.1"
rocket_codegen = "0.4.1"
ymal-rust = "0.4.3"